#!/bin/bash

if ! [[ $KERNEL_INSTALL_MACHINE_ID ]]; then
    exit 0
fi

ARCH=$(uname -m)

[[ -f /etc/default/grub ]] && . /etc/default/grub

# Can't assume a BLS capable bootloader on ppc64
if [[ x$GRUB_ENABLE_BLSCFG != xfalse &&
	  $ARCH != "ppc64" && $ARCH != "ppc64le" ]]; then
    exit 0
fi

COMMAND="$1"

case "$COMMAND" in
    add|remove)
        grub2-mkconfig --no-grubenv-update -o /boot/grub2/grub.cfg >& /dev/null
        ;;
    *)
        ;;
esac
